inherit_gem:
  vinted-rubocop:
    - .rubocop.yml

AllCops:
  TargetRubyVersion: 3.3.0
  DisplayCopNames: true
  Exclude:
    - db/**/*

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories/**/*.rb'
