default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>  # <-- host added
  port: <%= ENV.fetch("DB_PORT") { "3306" } %> # <-- port added
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'a' } %> # <-- password added